apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: hello-world-dispatch
  namespace: hello-world
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world-dispatch
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: hello-world-dispatch
  service:
    gateways:
    - public-gateway.istio-system.svc.cluster.local
    hosts:
    - '*'
    port: 80
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: gateway-error,connect-failure,refused-stream
    targetPort: 8080
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
  progressDeadlineSeconds: 60
  analysis:
    interval: 1m
    maxWeight: 50
    stepWeight: 25
    metrics:
    - interval: 1m
      name: request-success-rate
      thresholdRange: 
        min: 99
    threshold: 5
    webhooks:
    - metadata:
        cmd: hey -z 1m -q 10 -c 2 http://hello-world-dispatch-canary.hello-world:80/
      name: load-test
      timeout: 5s
      url: http://flagger-loadtester.kubeaddons-flagger/
